# Generated by Django 4.2.7 on 2023-11-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.RemoveField(
            model_name='login',
            name='password_reenter',
        ),
    ]
