# Generated by Django 4.2.7 on 2023-11-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites_Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountUser', models.CharField(max_length=60)),
                ('eventName', models.CharField(max_length=60)),
                ('eventImage', models.CharField(max_length=60)),
                ('startDate', models.CharField(max_length=60)),
                ('localTime', models.CharField(max_length=60)),
                ('venueName', models.CharField(max_length=60)),
                ('venueCity', models.CharField(max_length=60)),
                ('venueState', models.CharField(max_length=60)),
                ('venueAddress', models.CharField(max_length=60)),
                ('eventUrl', models.CharField(max_length=60)),
            ],
        ),
    ]
