# Generated by Django 4.2.7 on 2023-11-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites_library',
            name='eventImage',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='favorites_library',
            name='eventUrl',
            field=models.CharField(max_length=120),
        ),
    ]
