# Generated by Django 4.2.7 on 2023-11-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0002_alter_favorites_library_eventimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=60)),
                ('eventImage', models.CharField(max_length=120)),
                ('startDate', models.CharField(max_length=60)),
                ('localTime', models.CharField(max_length=60)),
                ('venueName', models.CharField(max_length=60)),
                ('venueCity', models.CharField(max_length=60)),
                ('venueState', models.CharField(max_length=60)),
                ('venueAddress', models.CharField(max_length=60)),
                ('eventUrl', models.CharField(max_length=120)),
            ],
        ),
    ]
